//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int Код_сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Должность { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
        public string Имя_и_отчество { get; set; }
        public System.DateTime Дата_рождения { get; set; }
    }
}
