//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Счет_фактуры
    {
        public int Номер_счет_фактуры { get; set; }
        public int Код_клиента { get; set; }
        public int Код_сотрудника { get; set; }
        public string Клиент { get; set; }
        public string Товар { get; set; }
        public int Количество { get; set; }
        public System.DateTime Дата { get; set; }
    }
}
