//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        public int Код_товара { get; set; }
        public int Код_производителя { get; set; }
        public string Наименование { get; set; }
        public int Артикул { get; set; }
        public string Тип { get; set; }
        public string Производитель { get; set; }
        public decimal Стоимость { get; set; }
    }
}
